services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    networks:
      app_network:
        ipv4_address: 172.20.0.20

  sensor-manager:
    image: 'docker.io/christiand9699/sensor-manager:0.0.1-SNAPSHOT'
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/mydatabase'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
    networks:
      app_network:
        ipv4_address: 172.20.0.10

  keycloak-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=keycloak'
      - 'POSTGRES_USER=keycloak'
      - 'POSTGRES_PASSWORD=keycloakpassword'
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      app_network:
        ipv4_address: 172.20.0.21

  keycloak:
    image: keycloak/keycloak
    depends_on:
      - keycloak-db
    environment:
      - 'KEYCLOAK_ADMIN=admin'
      - 'KEYCLOAK_ADMIN_PASSWORD=admin'
      - 'KC_DB=postgres'
      - 'KC_DB_URL=jdbc:postgresql://keycloak-db/keycloak'
      - 'KC_DB_USERNAME=keycloak'
      - 'KC_DB_PASSWORD=keycloakpassword'
    expose:
      - '8080'
    command: [ "start-dev" ]
    networks:
      app_network:
        ipv4_address: 172.20.0.22



volumes:
  postgres-data:
  keycloak-db-data:

networks:
  app_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
