services:

  postgres:
    image: 'postgres:17'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-SENSORS}
      POSTGRES_USER: ${POSTGRES_USER:-measurestream_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - '5432'
    networks:
      app_network:
        ipv4_address: 172.20.0.20

  sensor-manager:
    image: 'docker.io/christiand9699/sensor-manager:latest-dev-mario'
    depends_on:
      - postgres
    expose:
      - '8080'
    ports:
      - '8082:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/${POSTGRES_DB:-SENSORS}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-measurestream_admin}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      OS: "Windows_NT"
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx384m -XX:+UseG1GC -XX:ActiveProcessorCount=1
    networks:
      app_network:
        ipv4_address: 172.20.0.10

  mongodb:
    image: 'mongo:4.4.18'
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-MEASURES}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-secret}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
    ports:
      - '27017:27017'
    networks:
      app_network:
        ipv4_address: 172.20.0.23
    volumes:
      - mongo_data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  measure-manager:
    image: 'docker.io/christiand9699/measure:latest'
    depends_on:
      mongodb:
        condition: service_healthy
    expose:
      - '8080'
    ports:
      - '8081:8080'
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-secret}@mongodb:27017/${MONGO_INITDB_DATABASE:-MEASURES}?authSource=admin
      OS: Windows_NT
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx384m -XX:+UseG1GC -XX:ActiveProcessorCount=1
    networks:
      app_network:
        ipv4_address: 172.20.0.11

  keycloak-db:
    image: 'postgres:17'
    environment:
      POSTGRES_DB: ${POSTGRES_DB_KEYCLOAK:-keycloak}
      POSTGRES_USER: ${POSTGRES_USER_KEYCLOAK:-keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_KEYCLOAK:-keycloakpassword}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      app_network:
        ipv4_address: 172.20.0.21

  keycloak:
    image: keycloak/keycloak:26.4.2
    depends_on:
      - keycloak-db
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/${POSTGRES_DB_KEYCLOAK:-keycloak}
      KC_DB_USERNAME: ${POSTGRES_USER_KEYCLOAK:-keycloak}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD_KEYCLOAK:-keycloakpassword}
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    ports:
      - '8090:8080'
    command: ["start-dev"]
    networks:
      app_network:
        ipv4_address: 172.20.0.22
    healthcheck:
      test: ["CMD-SHELL", "exec 3<> /dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\\r\\nhost: http://localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3; if [ $? -eq 0 ]; then echo 'Healthcheck Successful'; exit 0; else echo 'Healthcheck Failed'; exit 1; fi;"]
      interval: 15s
      retries: 15
      start_period: 5s
      timeout: 2s

  dcc-service:
    image: "docker.io/christiand9699/dcc-service:latest-dev-mario"
    restart: unless-stopped
    depends_on:
      - postgres
    expose:
      - "8080"
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/${POSTGRES_DB:-SENSORS}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-measurestream_admin}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      GEMIMEG_BACKEND_URL: "http://gemimeg-backend:10001"
      GATEWAY_IAM_URL: "http://localhost:8080"
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx384m -XX:+UseG1GC -XX:ActiveProcessorCount=1
    networks:
      app_network:
        ipv4_address: 172.20.0.14

  gemimeg-backend:
    image: "docker.io/christiand9699/gemimeg-backend:latest-dev-mario"
    restart: unless-stopped
    depends_on:
      - dcc-service
    expose:
      - "10001"
    ports:
      - "3007:10001"
    environment:
      SERVER_PORT: 10001
      DCC_SERVICE_URL: "http://dcc-service:8080"
      GATEWAY_IAM_URL: "http://localhost:8080"
      FRONTEND_URL: "http://localhost:3006"
      JAVA_OPTS: "-Xmx512m -Xms256m -XX:+UseG1GC"
    networks:
      app_network:
        ipv4_address: 172.20.0.129

  gemimeg-frontend:
    image: "docker.io/christiand9699/gemimeg-frontend:latest-dev-mario"
    restart: unless-stopped
    depends_on:
      - gemimeg-backend
    ports:
      - "3006:80"
    environment:
      API_URL: "http://localhost:8080"
      BACKEND_HOST: "gemimeg-backend"
      BACKEND_PORT: "10001"
      GATEWAY_HOST: "localhost"
      GATEWAY_PORT: "8080"
    networks:
      app_network:
        ipv4_address: 172.20.0.128

  frontend:
    image: "docker.io/christiand9699/frontend-react:latest-dev-mario"
    restart: unless-stopped
    depends_on:
      - sensor-manager
      - measure-manager
      - dcc-service
    ports:
      - "5173:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    environment:
      VITE_API_URL: "http://localhost:8080"
      VITE_BACKEND_URL: "http://localhost:3007"
      VITE_GATEWAY_URL: "http://localhost:8080"
      VITE_DCC_SERVICE_URL: "http://localhost:8084"
      VITE_SENSOR_MANAGER_URL: "http://localhost:8082"
    networks:
      app_network:
        ipv4_address: 172.20.0.12

  grafana:
    image: grafana/grafana-enterprise
    restart: always
    profiles:
      - grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - /var/lib/grafana/plugins
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
      GF_INSTALL_PLUGINS: yesoreyeram-infinity-datasource
    networks:
      app_network:
        ipv4_address: 172.20.0.30

volumes:
  postgres-data:
  keycloak-db-data:
  mongo_data:
  grafana_data:

networks:
  app_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
