-- Database principali
CREATE DATABASE "SENSORS";
CREATE DATABASE "SETTINGS";
CREATE DATABASE "CALIBRATOR";

-- Utente principale
GRANT ALL PRIVILEGES ON DATABASE "SENSORS" TO measurestream_admin;
GRANT ALL PRIVILEGES ON DATABASE "SETTINGS" TO measurestream_admin;
GRANT ALL PRIVILEGES ON DATABASE "CALIBRATOR" TO measurestream_admin;

-- Crea schema DCC nel database SENSORS
\c SENSORS;
CREATE SCHEMA IF NOT EXISTS dcc;
GRANT ALL PRIVILEGES ON SCHEMA dcc TO measurestream_admin;