GRAFANA_API_KEY: glsa_zZfUU4YUJbTAE2SR7PqkY35nk2ZiLJbW_229bacdd

spring:
  application:
    name: iam_module
  main:
    web-application-type: servlet

  cloud:
    gateway:
      mvc:
        http-client:
          type: AUTODETECT
        routes:


          - id: sensor-manager-nodes
            uri: http://172.20.0.10:8080
            predicates:
              - Path=/API/nodes/**
            filters:
              - TokenRelay

          - id: sensor-manager-dcc
            uri: http://172.20.0.10:8080
            predicates:
              - Path=/API/dcc/**
            filters:
              - TokenRelay

          - id: sensor-manager-measurementunit
            uri: http://172.20.0.10:8080
            predicates:
              - Path=/API/measurementunits/**
            filters:
              - TokenRelay

          - id: sensor-manager-controlunits
            uri: http://172.20.0.10:8080
            predicates:
              - Path=/API/controlunits/**
            filters:
              - TokenRelay

          - id: measure-manager
            uri: http://172.20.0.11:8080
            predicates:
              - Path=/API/measures/**
            filters:
              - TokenRelay

          #FRONTEND
          - id: frontend
            uri: http://172.20.0.12:80
            predicates:
              - Path=/ui/**

          - id: home
            uri: http://localhost:8080
            predicates:
              - Path=/
            filters:
              - RedirectTo=301,https://www.christiandellisanti.uk/ui

          - id: grafana
            uri: http://172.20.0.30:3000
            predicates:
              - Path=/grafana/**
            filters:
              - StripPrefix=1
              - RemoveResponseHeader=X-Frame-Options

          #- id: keycloak
          #  uri: http://172.20.0.22:8080 # Keycloak in locale sulla 8081
          #  predicates:
          #    - Path=/auth/**
          #  filters:
          #    - StripPrefix=1



        form-filter:
          enabled: false

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://auth.christiandellisanti.uk/realms/measurestream
            #authorization-uri: http://christiandellisanti.uk/realms/measurestream/protocol/openid-connect/auth
            #token-uri: http://172.20.0.22:8080/realms/measurestream/protocol/openid-connect/token
            #user-info-uri: http://172.20.0.22:8080/realms/measurestream/protocol/openid-connect/userinfo
            #jwk-set-uri: http://172.20.0.22:8080/realms/measurestream/protocol/openid-connect/certs
            #user-name-attribute: preferred_username

        registration:
          gateway:
            provider: keycloak
            client-id: gateway
            client-secret: i3KBTdwpup1nlOEJBNtQHTjFqiycCNQ4
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: https://www.christiandellisanti.uk/login/oauth2/code/gateway
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1




server:
  max-http-request-header-size: 1MB
  port: 8080


#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.cloud.gateway: DEBUG