spring:
  application:
    name: iam_module

  cloud:
    gateway:
      mvc:
        http-client:
          type: autodetect
        routes:
          #LAB 1 document_store
          - id: sensor-manager
            uri: http://172.20.0.10:8080
            predicates:
              - Path=/API/nodes/**
            filters:
              - TokenRelay

          #FRONTEND
          - id: frontend
            #uri: http://172.20.0.8:5173
            uri: http://localhost:5173
            predicates:
              - Path=/ui/**



        form-filter:
          enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://172.20.0.22:8080/realms/measurestream
        registration:
          gateway:
            provider: keycloak
            client-id: gateway
            client-secret: i3KBTdwpup1nlOEJBNtQHTjFqiycCNQ4
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/gateway
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1


keycloak:
  datasource:
    url: jdbc:postgresql://keycloak-db/keycloak
    username: keycloak
    password: keycloakpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

server:
  max-http-request-header-size: 1MB
